name: ktlint CI

permissions:
  actions: write
  checks: write
  contents: write

on:
  push:
    branches:
      - "master"
      - "docs/actions"
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md

jobs:
  ktlint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17

      - name: set up AD_UNIT_ID
        run: echo "AD_UNIT_ID=``" >> local.properties

      - name: set up AD_APPLICATION_ID
        run: echo "AD_APPLICATION_ID=``" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlintFormat
        run: ./gradlew ktlintFormat

      - name: Run ktlint
        run: ./gradlew ktlintMainSourceSetCheck

      - name: Run Push
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push