#on: push
#jobs:
#  add_text:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Set up Java 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: microsoft
#          java-version: 17
#
#      - name: set up AD_UNIT_ID
#        run: echo "AD_UNIT_ID=``" >> local.properties
#
#      - name: set up AD_APPLICATION_ID
#        run: echo "AD_APPLICATION_ID=``" >> local.properties
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Run ktlintFormat
#        run:
#          ./gradlew ktlintFormat
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "[Auto] ktlintFormat"
#          git push
on: push
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Hello GitHub Actions!" >> hello.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push