on: push
jobs:
  add_text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./gradlew ktlintFormat
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[Auto] ktlintFormat"
          git push